### ISSUE TITLE
pretrain model release

### ISSUE THREAD

**Issue by jingziyou** [lixiaopeng123456/DADRnet#1]
Hi,
when the pre-training model will be released

**Comment by Lxp2014** [comment]
Hello, I am busy preparing for a conference paper recently. All pretrained models will be released by the end of this month.

**Comment by duanpingtin** [comment]
> Hello, I am busy preparing for a conference paper recently. All pretrained models will be released by the end of this month.

Hi, when the train.py  and pre-training model will be released.

**Comment by Lxp2014** [comment]
> > Hello, I am busy preparing for a conference paper recently. All pretrained models will be released by the end of this month.
> 
> Hi, when the train.py and pre-training model will be released.
The pre-training model is in checkpoints/restoration/mapping_quality
